name: Check code style

on:
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 20.15.1
      - run: npm ci
      - name: Checking format
        run: npm run format:check
      - name: Run lint
        run: npm run lint
