name: Check code style

on:
  pull_request:
    branches:
      - main

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Setup Node
        uses: actions/setup-node@v4.0.3
        with:
          node-version-file: .nvmrc
      - run: npm ci

      - name: Checking format
        run: npm run format:check
      - name: Run lint
        run: npm run lint
